project:
  type: website

website:
  title: "How To Liederbuch"
  #author: ""
  #image: ""
  #favicon: ""
  #site-url: ""
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
  navbar: 
    background: light
    #logo: ""
    title: "How To Liederbuch"
    left:
      - text: "Moin"
        href: index.qmd
      - text: "Einführung"
        href: vorbereitung.qmd
      - text: "Doku"
        href: doku.qmd
  sidebar: 
    - id: vorbereitung
      title: "Vorbereitung"
      style: floating
      collapse-level: 2
      align: left
      contents:
        - section: "Vorbereitung"
          href: vorbereitung.qmd
          contents:
            - lilypond_einrichten.qmd
            - frescobaldi_einrichten.qmd
            - git_einrichten.qmd
        - section: "Lieder setzen"
          href: liedersetzen.qmd
          contents: 
            - beispiel_liedersetzen.qmd
            - branch_und_pullrequest.qmd
            - liedlayout.qmd
            - liederbuecher_machen.qmd
            - repostruktur.qmd
            
    - id: doku
      title: "Doku"
      style: floating
      collapse-level: 2
      align: left
      contents:
        - section: "Doku"
          href: doku.qmd
          contents:
            - lifehacks.qmd
            - git_verstehen.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme: 
      light: cosmo
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

freeze: true

editor: visual

