project:
  type: book

book:
  title: "How To Liederbuch"
  author: ""
  date-format: DD.MM.YYYY
  date: "2/10/2025"
  search: true
  chapters:
    - index.qmd
    - vorbereitung.qmd
    - part: lilypond_einrichten.qmd
    - part: frescobaldi_einrichten.qmd
    - part: git_einrichten.qmd
    - lifehacks.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

