project:
  type: website
  resources: CNAME

website:
  title: "How To Liederbuch – Das Liederpool-Projekt"
  description: "Wir sind das Liederpool-Projekt und wir machen Liederbücher. Auf dieser Website wollen wir eine möglichst vollständige Dokumentation unseres Systems sowie Tutorials und How-To’s bereitstellen, um den Einstieg und die Arbeit mit unserem System zu erleichtern."
  #image: ""
  favicon: "images/logo_buebuebue.svg"
  #site-url: ""
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
  reader-mode: true
  navbar: 
    background: primary
    logo: "images/logo_buebuebue.svg"
    title: "How To Liederbuch – Das Liederpool-Projekt"
    left:
      - text: "Moin"
        href: index.qmd
      - text: "Einführung"
        href: vorbereitung.qmd
      - text: "Doku"
        href: doku.qmd
      - text: "Changelog"
        href: changelog.qmd
  sidebar: 
    - id: vorbereitung
      title: "Vorbereitung"
      style: floating
      collapse-level: 2
      align: left
      contents:
        - section: "Vorbereitung"
          href: vorbereitung.qmd
          contents:
            - lilypond_einrichten.qmd
            - frescobaldi_einrichten.qmd
            - git_einrichten.qmd
            - pyyaml.qmd
        - section: "Lieder setzen"
          href: liedersetzen.qmd
          contents: 
            - beispiel_liedersetzen.qmd
            - branch_und_pullrequest.qmd
            - liedlayout.qmd
            - liederbuecher_machen.qmd
            - repostruktur.qmd
            
    - id: doku
      title: "Doku"
      style: floating
      collapse-level: 2
      align: left
      contents:
        - section: "Doku"
          href: doku.qmd
          contents:
            - section: "Liedersetzen-Prozess"
              contents:
                - liedsatz_standards.qmd
                - metadaten.qmd
                - musikalischer_inhalt.qmd
                - liedlayout_doku.qmd
                - liederbuch_layout.qmd
                - quellen.qmd
                - quellenlinks.qmd
                - lifehacks.qmd
            - section: "Review-Prozess"
              contents:
                - git_verstehen.qmd
                - review.qmd
                - markdown_tutorial.qmd
  open-graph:
    site-name: "How-To Liederbuch – Das Liederpool-Projekt"
    locale: de_DE
  announcement: 
    #icon: exclamation-triangle-fill # Warning
    icon: check-square-fill #success
    dismissable: false
    content: "Die Probleme unter Windows 10/11 sind nun behoben. Allerdings ist es nun erforderlich, ebenfalls „PyYAML“ zu installieren. In Kürze wird es dazu Anleitungen geben."
    type: success
    position: below-navbar

bibliography: references.bib
lang: de
fig-cap-location: top

format:
  html:
    toc: true
    theme: 
      light:
        - sandstone
        - theme.scss
      dark:
        - darkly
        - theme.scss
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

freeze: true

editor: visual

