---
title: "Lied-Layout"
format: html
---

In diesem Abschnitt der Doku zeigen wir Lösungen für Probleme oder Herausforderungen, die sich aus der Arbeit mit unserem System ergeben. Vieles davon wurde von tux entwickelt und befindet sich in den `lilypond-common-includes`, bei manchen Themen verweisen wir auch einfach nur auf die LilyPond-Doku. Dieser Teil ist fokussiert auf die Layout-Fragen.

::: callout-note
Anmerkung: Die Codebeispiele sind teilweise vereinfacht und verkürzt, um die Probleme und Lösungen möglichst einfach zu erklären. Sie sind damit nicht zwangsläufig eins zu eins übertragbar und anwendbar (und finden sich teils nicht eins zu eins im Liederpool wieder).
:::

# Eingriffe ins „Musik“-Layout

## Transponieren

Viele Lieder sind in verschiedenen Tonarten verbreitet. Im Liederpool sollte sich grundsätzlich an die Originaltonart gehalten werden. Wenn die Tonart in einem Liederbuch angepasst werden soll, funktioniert dies mit dem Befehl `\transposeGlobal x y`. Mit `x` und `y` wird dabei der Tonsprung bezeichnet. Es bietet sich an, dafür die Tonarten zu nutzen, tatsächlich ist aber lediglich der Abstand entscheidend. Der Befehl kann einfach irgendwo in der Datei aufgerufen werden, am besten nicht innerhalb anderer Teile/Variablen.

Beispiel: Wir wollen ein Lied statt in Fis-Dur in C-Dur setzen. Dann schreiben wir: `\transposeGlobal fis c,`. In diesem Falle müssen wir vermutlich die Tonhöhe anpassen, da der Sprung sehr groß ist. Das funktioniert wie in LilyPond gewohnt mit `,` bzw. `'`.

## Römische Ziffern {#sec-romanstanza}

Römische Ziffern (`I`, `II` etc.), um zum Beispiel Übersetzungen mit einem anderen System zu nummerieren als den Originaltext, können erreicht werden, in dem vor den Ausdruck `#(stanza 1)` die Funktion `\romanStanza` aufgerufen wird.

Beispiel:

``` lilypond
TEXT = \markuplist {
  \group-verses {
    \chordlyrics { \romanStanza \firstVerse }
  }
}
```

# Layout der Strophen

## Zeilenumbrüche in den Strophen {#sec-zeilenumbrueche}

Problem: Verschiedene Liederbücher haben verschiedene Formate, weswegen es keinen idealen Zeilenumbruch für alle Liederbücher gibt.

Lösung: Versumbrüche werden in der Variable `verse-breaks` anhand von (unsichtbaren) Pausen (`s`)und `\break`-Befehlen bewirkt. Diese Variable wird dann mittels `\override`-Befehl vor den entsprechenden Versen im `TEXT`-Part eingebunden. Beispiel: `` \override #`(verse-break-voice . ,verse-breaks) ``. `verse-break-voice` erstellt eine (unsichtbare) Stimme mit den Umbrüchen aus `verse-breaks` und wird auch für den Fall gesetzt, dass es Strophen und einen Refrain gibt. In dem Falle wird das `\override` immer vor den unterschiedlichen Strophen neu gesetzt.

::: callout-warning
Achtung: `\override` gilt immer nur für das folgende Element, zum Beispiel ein Vers oder ein `\group-verses`-Ausdruck.

Für mehrere Ausdrücke kann stattdessen `\override-lines` genutzt werden. Das könnte mit dem unten stehenden Beispiel dann so aussehen:

``` lilypond
TEXT = \markuplist {
  \override-lines #`(verse-break-voice . ,verse-breaks)
  {
  \group-verses {
    \chordlyrics \firstVerse
    \chordlyrics \secondVerse
    \override #`(verse-break-voice . ,ref-breaks)
    \chordlyrics \refLyrics
  }
  \group-verses {
    \chordlyrics \thirdVerse
  }
  }
}
```

Das zu Beginn gesetzte Override gilt nun auch für die unteren Group-Verses.
:::

Codebeispiel, bei dem Refrain und Strophe auf eine Seite (und damit in ein `\group-verses`) gedruckt werden:

``` lilypond
verse-breaks = {
  s2.*4 \break %s2.*4 bedeutet, dass s2. 4 mal wiederholt wird
  s2.*4 \break
  s2.*4 \break
}

ref-breaks = {
  s2.*2 \break
  s2.*2 \break
}

TEXT = \markuplist {
  \override #`(verse-break-voice . ,verse-breaks)
  \group-verses {
    \chordlyrics \firstVerse
    \chordlyrics \secondVerse
    \override #`(verse-break-voice . ,ref-breaks)
    \chordlyrics \refLyrics
    \chordlyrics \thirdVerse
  }
}
```

## Strophentext kleiner machen

Der Strophentext im alten (!) System kann mit dem Befehl `\fontsize #-1` verkleinert werden. Der Befehl kommt an den Anfang des Markup-Blocks.

Im neuen System verändert sich die Textgröße analog zur Score-Größe (siehe @sec-size).

``` lilypond
TEXT = \markuplist {
  \fontsize #-1
  \group-verses {
    %…
  }
}
```

## Abstand zwischen Strophen

Zwischen Strophen oder auch gruppierten Strophen und ganz generell in Markup kann ein Abstand zwischen zwei Objekten mittels des Befehls `\vspace #0` erzeugt werden, wobei die Zahl beliebig groß oder klein (auch negativ) gesetzt werden kann.

## Abstand zwischen Strophen innerhalb der Group-Verse-Umgebung

Innerhalb eines `\group-verses` kann der Abstand zwischen den Strophen einheitlich mit dem Befehl `\override #'(verse-vspace . 0.8)` modifiziert werden. Der Standardwert beträgt `1`. Werte können auch negativ sein. Der Override-Befehl wird vor die Group-Verses-Umgebung geschrieben.

``` lilypond
TEXT = \markuplist {
  \override #'(verse-vspace . 0.8)
  \group-verses {
    %…
  }
}
```

## Zeilenabstand (Abstand innerhalb der Strophen)

Der Zeilenabstand, also der Abstand der Verse innerhalb der Strophen zueinander, kann mit dem Befehl `\override #'(intraverse-vspace . 0.3)` beeinflusst werden. Der Standardwert beträgt `0`. Werte können auch negativ sein. Der Befehl muss vor die Group-Verses-Umgebung geschrieben werden.

``` lilypond
TEXT = \markuplist {
  \override #'(intraverse-vspace . 0.3)
  \group-verses {
    %…
  }
}
```

## Spalten

Die Strophen können auch in Spalten gruppiert werden. Das funktioniert mit dem Befehl `\override #'(verse-cols . 2)`. Die Zahl gibt die Anzahl der Spalten an. Die Anordnung erfolgt von oben nach unten und dann in der nächsten Spalte wieder von oben nach unten. Mit dem Befehl `\override #'(verse-ordering-horizontal . #t)` kann dieses Verhalten beeinflusst werden. Der Befehl `\override #'(verse-hspace . -5)` ermöglicht die Veränderung des Abstands zwischen den Spalten.

``` lilypond
TEXT = \markuplist {
  \override #'(verse-cols . 3) % 3 Spalten
  \override #'(verse-ordering-horizontal . #t) % Verse horizontal fortlaufend anordnen
  \override #'(verse-hspace . -5) % Abstand zwischen Spalten geringer machen
  \group-verses {
    %…
  }
}
```

# Layout von Inline-Scores

Inline-Scores sind Notensätze (Scores), die innerhalb der TEXT-Umgebung genutzt werden, also zum Beispiel eine Bridge oder auch eine Coda.

## Abstand der Notenzeilen

Der Abstand der Notenzeilen von Inline-Scores kann angepasst werden mit dem Befehl `\override #'(baseline-skip . 1)`.

``` lilypond
TEXT = \markuplist {
  \group-verses {
    \override #'(baseline-skip . 1)
    \score {
      \inline-score
      \BRIDGE
      \layout { \generalLayout}
    }
  }
}
```

# Seitenlayout

## Ausgabe-Größe {#sec-size}

Um Platz zu sparen, kann es hilfreich sein, die Größe des Staffs (wozu effektiv fast alle Ausgabe-Elemente gehören: Noten, Lyrics, Akkorde und somit auch die Strophen) abweichend von den globalen Liederbucheinstellungen anzupassen. Das erfolgt mit der Ergänzung des `LAYOUT`-Blocks:

``` lilypond
LAYOUT = \layout {
  \LAYOUT
  size = 15 %hier die gewünschte Größe anpassen
}
```

Das ergänzt den in den Skripten bereits existierenden `LAYOUT`-Block um die Staff-Size, die effektiv mit dem Scheme-Befehl `#(layout-set-staff-size 13.8)` überschrieben wird. Aus technischen Gründen funktioniert der nicht immer zuverlässig, weshalb es den oben genannten Befehl für diesen Zweck gibt.

## Der `\paper`-Block

Im `\paper`-Block können etliche Schrauben am Layout gedreht werden. Dabei nutzen wir ausschließlich schon vorhandene LilyPond-Funktionen und verweisen an dieser Stelle jeweils auf die offizielle LilyPond-Doku.

Der `\paper`-Block ist Teil des `HEADER`’s und wird an die folgende Stelle in der Layout-Datei eingefügt:

``` lilypond
HEADER = \bookpart {
  \paper {
    %hier kommt alles rein, was in den Paper-Block gehört
  }
  \header {
    \basicSongInfo
    %infotext = ""
  }
}
```

### Seitenanzahl eines Liedes bestimmen

Wenn ein Lied auf eine Seite gequetscht werden soll, geht das mit dem Befehl `page-count = #1`, wobei die Nummer hinter dem `#`-Zeichen jeweils für die Anzahl der Seiten steht. Mehr dazu in der [LilyPond-Doku](https://lilypond.org/doc/v2.24/Documentation/notation/other-paper-variables#paper-variables-for-page-breaking).

### Abstand zwischen Titel und Noten

Der Abstand zwischen Titel und Noten wird mit `markup-system-spacing.padding = 4` definiert. Mehr dazu in der [LilyPond-Doku](https://lilypond.org/doc/v2.24/Documentation/notation/flexible-vertical-spacing-paper-variables#list-of-flexible-vertical-spacing-paper-variables).

### Abstand zwischen Seitenrand und oberstem Notensystem

Das kann hilfreich sein, um zum Beispiel Noten auf der zweiten Seite weiter unten anfangen zu lassen. Wenn etwas anderes dort steht (z.B. Titel oder Text), greift das nicht. Der Befehl lautet: `top-system-spacing.padding = 6`. Mehr dazu in der [LilyPond-Doku](https://lilypond.org/doc/v2.24/Documentation/notation/flexible-vertical-spacing-paper-variables#list-of-flexible-vertical-spacing-paper-variables).

### Abstand zwischen den Systemen

Der Abstand zwischen den Notensystemen kann mittels `system-system-spacing.padding = 1` angepasst werden. Mehr dazu in der [LilyPond-Doku](https://lilypond.org/doc/v2.24/Documentation/notation/changing-spacing).

### Keine Seitennummer

Wenn die Seitennummer nicht geprintet werden soll, kann der Befehl `print-page-number = ##f` verwendet werden. Mehr dazu in der [LilyPond-Doku](https://lilypond.org/doc/v2.25/Documentation/notation/paper-variables-for-page-numbering).

## Größe des Bildtitels

Wenn ein Lied anstatt eines Schrifttitels ein Bildtitel hat (also eine eps-Datei, die im Layout-Ordner liegt), dann kann die Größe dieser eps-Datei mittels der Variable `titlesize = 11` angepasst werden, die in den Header eingefügt werden muss, also:

``` lilypond
HEADER = \bookpart {
  \header {
    \basicSongInfo
    titlesize = 11 %hier die Zahl anpassen
  }
}
```

## Abstand des Titels zum oberen Seitenrand

Der Abstand des Titels (egal ob Bild oder Schrift) zum oberen Seitenrand kann mittels der Variable `titletopspace = 2` eingestellt werden, die ebenfalls in den Header muss:

``` lilypond
HEADER = \bookpart {
  \header {
    \basicSongInfo
    titletopspace = 2 %hier die Zahl anpassen
  }
}
```

# Illustrationen

Illustrationen bekommen im einfachsten Fall eine ganze `imagepage`. Das wird in der Liederbuchdatei bearbeitet. Wenn eine Illustration auf ein „Liedblatt“ drauf kommt, wird dies in der Layout-Datei des Liedes organisiert. Das Bild muss für diesen Fall im Ordner des Liedes gespeichert sein und idealerweise als EPS-Datei vorliegen (im Zweifel hilft Inkscape).

Objekte wie Illustrationen an die gewünschte Stelle zu verschieben, kann etwas frickelig sein, aber funktioniert mit verschiedenen Methoden.

## Verschieben von Objekten

Die Funktion `\translate #'(x . y)` verschiebt das nächste, was geprinted wird, nicht an die eigentliche Stelle, sondern verschiebt es um die Koordinaten `x` und `y` (jeweils numerische Werte). Ausprobieren hilft.
