---
title: "Nützliche Lifehacks"
---

## Frescobaldi-Lifehacks

-   Du kannst die Silben eines Textes automatisiert trennen: Text auswählen und unter `Werkzeuge/Musical Transformations/Liedtext/Trennungsstriche in Text einführen` oder einfach `Strg + L`. Achtung! Die Funktion funktioniert leider nicht absolut fehlerfrei, deswegen definitiv nochmal Korrektur drüber lesen.

-   Du kannst Noten ganz einfach transponieren, was in diesem Falle meint, dass sich der tatsächliche Code verändert: entsprechenden Code auswählen unter `Werkzeuge/Musical Transformations/Tonhöhen/Transponieren`. Dazu wichtig: Abschnitt auswählen und im Dokument vorher *temporär* `\language "deutsch"` aufrufen.

-   Auch Notenlängen Halbieren oder Verdoppeln geht sehr einfach: entsprechenden Code auswählen `Werkzeuge/Musical Transformations/Rythmus/` und dann auf `Notenlänge verdoppeln` bzw. `Notenlänge halbieren`.

-   Ebenfalls kann eine bestimmte rhythmische Form übernommen werden: `Werkzeuge/Musical Transformations/Rhythmus/`.

-   Lange Zeilen können im Editor standardmäßig umgebrochen werden: Unter `Bearbeiten/Einstellungen/Editor-Einstellungen/Einstellungen zur Ansicht` -\> Haken setzen.

-   Zahlreiche LilyPond-Codeschnipsel gibt es unter `Schnipsel`. Das wollen wir künftig noch mehr ausbauen.

## LilyPond-Lifehacks {#sec-lilypond}

Falls du mal gerade unterwegs bist und nur ein Handy zur Verfügung hast, aber grad ein Lied notieren willst, gibt es zwei fantastische Möglichkeiten Möglichkeiten:

-   Lilypond im Browser: <https://www.hacklily.org/>

-   Telegrambot: LilyPondBot
