---
format: html
---

# Einrichtung von LilyPond

LilyPond ist die Software, die wir zum Noten setzen benutzen. Als erstes müssen wir LilyPond bei dir installieren.

## LilyPond installieren

1.  Gehe auf <https://lilypond.org/> und wähle unter `Downloads` die neueste LilyPond-Version. Grundsätzlich ist immer die stabile Version zu bevorzugen (alle geraden Zahlen, z.B. `2.24`). Unser System funktioniert aber (unter Windows) erst ab der Version `2.25.24`, das ist eine Entwicklerversion (zu erkennen an der ungeraden `25`).

2.  Nun sollte der Download starten. Gehe in den Ordner und entpacke den Download. Herauskommen sollte ein Ordner namens `lilypond-*`, wobei `*` die Versionsnummer darstellt.

3.  Fertig. Allerdings solltest du den Ordner an einen Ort legen, an dem er nicht verschoben wird. Zu empfehlen ist

    -   unter Windows: Ins Verzeichnis C und dann in den Ordner `Programme (x86)`. Dort sind auch andere Programmordner, deswegen ergibt das dort Sinn.

    -   unter Linux: Zum Beispiel ins Verzeichnis `home`.

Jetzt hast du LilyPond installiert. Damit es jetzt auch Spaß macht, mit LilyPond zu arbeiten, benötigst du noch Frescobaldi.
