---
title: "Quellen"
format: html
---

Uns ist eine Dokumentation der Originalfassung eines Liedes wichtig. Nicht, weil wir meinen, dass das die einzig richtige Version wäre, sondern um die Möglichkeit zu geben, auch die Originale sich anzuschauen und in Liederbüchern zu verwenden. Dafür betreiben wir Quellenrecherche in alten und neuen Liederbüchern. Es ist nicht immer einfach zu sagen, ob ein Liederbuch eine eher verlässliche Quelle ist. Als Einschätzungshilfe, insbesondere für „Originalquellen“ sammeln wir hier relevante Informationen über aus unserer Sicht gut verwendbare bzw. sehr gebräuchliche Liederbücher.

## Der Turm A / B / Der schräge Turm

Der Turm ist eigentlich eine Liederbuchreihe, die von helm im Voggenreiter-Verlag herausgegeben wurde. Die Versionen von Liedern unterscheiden sich öfter vom Original, sind aber oft auch sehr verbreitet. Der Turm ist sehr prägend für das jugendbewegte Liedgut gewesen.

## Die Silberspringe

…sind zwar immer eine Originalquelle für Lieder aus dem Zugvogel, allerdings lassen die Qualität der Notensätze zu wünschen übrig. Einerseits werden die Lieder vom ZV und den Autor\*innen teilweise selbst anders gesungen, andererseits gibt es auch hin und wieder Notationsfehler oder Vereinfachungen, die wir grundsätzlich natürlich nicht übernehmen wollen.

## Der Liedertrödler

…ist das zweite olka-Liederbuch aus dem Verlag der Jugendbewegung und ist somit Originalquelle. Die Akkordnotation ist etwas speziell mit [Generalbass](generalbass.qmd). Bitte beachtet unsere Seite dazu!

## olkas Lieder

…ist das erste olka-Liederbuch aus dem Verlag der Jugendbewegung und ist somit Originalquelle. Die Akkordnotation ist etwas speziell mit [Generalbass](generalbass.qmd). Bitte beachtet unsere Seite dazu!

## Querfeldein – Ein- und Zweistimmige Fahrtenlieder mit Gitarre ad lib.

…wurde von alf (Alfred Zschiesche) höchstselbst herausgegeben und gilt somit für Lieder von alf als Originalquelle.

## Klingende Fahrt – Ein Liederbuch für Gesang und Gitarre

…wurde von alf (Alfred Zschiesche) höchstselbst herausgegeben (1960) und gilt somit für Lieder von alf als Originalquelle.

## Das Klampfenlied – Ein Fahrtenliederbuch für Gesang und Gitarre

…wurde von alf (Alfred Zschiesche) höchstselbst herausgegeben (1958) und gilt somit für Lieder von alf als Originalquelle.

## Sing mir, Morena – Lieder zur Gitarre aus Spanien, Südfrankreich, Litauen, Dalmatien

…wurde von alf (Alfred Zschiesche) höchstselbst herausgegeben (1964) und gilt somit für Lieder von alf als Originalquelle.

## Lieder der Eisbrechermannschaft

…wurde 1933 von tusk (Eberhard Koebel) herausgegeben und dient für einige Lieder als Originalquelle, die aus der dj.1.11 stammen.

## tejos Lieder

…erschienen im Verlag der Jugendbewegung. Gilt als Originalquelle.

## Unterm Nordstern. Lieder von turi

…erschienen im Verlag der Jugendbewegung. Gilt als Originalquelle.

## Carmina Nerothana (Werner Helwig)

…erschienen im Verlag der Jugendbewegung. Gilt als Originalquelle.

## Liedblätter Deutscher Jugend (Liederbuchreihe)

Die LDJ wurden herausgegeben vom Verlag der Jugendbewegung und wurden in der Regel in enger Zusammenarbeit mit den Autor\*innen erstellt. Deswegen gelten sie als Originalquelle.

## Codex Patomomomensis

…ist ein sehr umfangreich recherchiertes Liederbuch, das sich auch auf die Suche nach Originalquellen gemacht hat. Von daher genießt der Codex bei uns einen exzellenten Ruf. Zum Inhaltsverzeichnis geht’s [hier](https://www.zauberwald-verlag.de/codex/inhaltsverzeichnis.htm) und da findet sich auch die Errata-Liste, die grundsätzlich immer hinzugezogen werden sollte.
